#pragma config(Sensor, in1,    leftBumper,     sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, in4,    rightBumper,    sensorEV3_Touch, modeEV3Bump)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void wander() {
	// While (bumper not engaged)
	// move forward for random time
	// pick random direction d = (left/right)
	// stop 1 sec
	// swing turn in direction d for random time
	// stop 1 sec
}

void objectDetected() {
			// If (right side bumper hit)
			// wait 10 milliseconds
			// stop 1 sec
			// If (left side bumper hit)		// Both hit
				// make sound
				// back up short distance
				// stop 2 secs
				// turn in random direction
				// stop 1 sec
			// else													// Only right
				// back up short distance
				// stop 1 sec
				// turn left
				// stop 1 sec


		// Else if (left side bumber hit)
			// wait 10 milliseconds
			// stop 1 sec
			// If (right side bumper hit)		// Both hit
				// make sound
				// back up short distance
				// stop 2 secs
				// turn in random direction
				// stop 1 sec
			// else													// Only left
				// back up short distance
				// stop 1 sec
				// turn right
				// stop 1 sec
}

void playSound() {

	/*setSoundVolume(127);
	playTone(400, 50); // A for 0.05 seconds
	wait1Msec(50);		 // A for 0.05 seconds
	*/
}

task main() {
	while (true) {
		wander();
	}
}