#pragma config(Sensor, S1,     leftBumper,     sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S4,     rightBumper,    sensorEV3_Touch, modeEV3Bump)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program is solely used to test robot functionality

void playSound() {

	//setSoundVolume(127);
	playTone(400, 50); // A for 0.05 seconds
	wait1Msec(50);		 // A for 0.05 seconds

}

void moveNCoast() {

	while (true) {
		// Test run
		motor[leftMotor] = 127;		// Full speed forward
		motor[rightMotor] = 127;	// Full speed forward
		wait1Msec(1000);	// 1 seconds

		for (int i = 127; i >= 0; i--) {
			motor[leftMotor] = 	i;		// Full speed forward
			motor[rightMotor] = i;	// Full speed forward
			wait1Msec(100);	// 0.1 second
		}

		motor[leftMotor] = 0;			// Stop
		motor[rightMotor] = 0;		// Stop
		wait1Msec(3000);	// 3 seconds
	}
}

// Tests the wandering function for challenge 1
void wander() {

	//

	// Onstart Direction:
	//	forward for rand amount of time
	// On Previously left turn:
	//	next left = 10%
	//	next right = 90%
	// On Previously right turn:
	//	next left = 90%
	//  next right = 10%



	// While (bumper not engaged)
	// move forward for random time
	// pick random direction d = (left/right)
	// stop 1 sec
	// swing turn in direction d for random time
	// stop 1 sec
}

task main() {

	while (true) {
		wander();
	}

/*
	resetBumpedValue(rightBumper);

	while (true) {
		if (getBumpedValue(rightBumper) > 0) {
			playSound();
			resetBumpedValue(rightBumper);
		}
	}
*/
}